FROM amazonlinux:2022

LABEL maintainer="Mark Meredith <mark.meredith@netl.doe.gov>"

RUN yum -y update \
    && yum install -y \
    meson \
    rpm-build \
    rpm-devel \
    rpmdevtools \
    rpmlint \
    && yum clean all

WORKDIR /root

COPY RPM RPM/
COPY VERSION ./
COPY meson.build ./
COPY openClose.sh ./
COPY src/ src/
COPY subprojects/ subprojects/
COPY test/ test/

## TODO: Build capd.rpm
# RUN rpmbuild -ba RPM/capd.spec

CMD [ "/bin/bash" ]
