FROM amazonlinux:2022

LABEL maintainer="Mark Meredith <mark.meredith@netl.doe.gov>"

RUN yum -y update \
    && yum install -y \
    gcc \
    meson \
    openssl-devel \
    rpm-build \
    rpmlint \
    && yum clean all

WORKDIR /root

RUN mkdir -p rpmbuild/SOURCES
COPY build-src/meson-dist/capd-v22.2.17.tar.xz ./rpmbuild/SOURCES
ADD ${SRC_TAR} ./

RUN env SRC_TAR="${SRC_TAR}" rpmbuild -v -ba packaging/RPM/capd.spec

CMD [ "/bin/bash" ]
