name: C CI

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install Poetry
      run: pip install --no-cache-dir poetry==1.1.13

    - name: Install Poetry environment
      run: poetry install

    - name: Configure
      run: poetry run meson build

    - name: Build
      run: poetry run meson compile -C build

    - name: capd Tests
      run: poetry run meson test -C build

    - name: mfa_program Tests
      run: poetry python -m pytest --mypy

    - name: mfa_program Lint
      run: poetry python -m pylint
