name: C CI

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: meson build

    - name: Build
      run: meson compile -C build

    - name: Test
      run: meson test -C build
